# PyTorch Basics

## Init, helpers, utils, ...

In [1]:
%matplotlib inline

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

In [3]:
from pprint import pprint

import matplotlib.pyplot as plt
import numpy as np
from IPython.core.debugger import set_trace

# Tensors
tensors - the atoms of machine learning

## Tensors in numpy and pytorch

In [4]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [5]:
# numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# torch
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [7]:
# numpy
X = np.random.random((5, 3))
X

array([[0.56010843, 0.46883419, 0.5455064 ],
       [0.23870143, 0.93548046, 0.46084231],
       [0.04994953, 0.60582373, 0.51687707],
       [0.26741617, 0.66721255, 0.85416748],
       [0.89914931, 0.73709758, 0.06132707]])

In [8]:
# pytorch
Y = torch.rand((5, 3))
Y

tensor([[0.3912, 0.6045, 0.0014],
        [0.2513, 0.0729, 0.3584],
        [0.4904, 0.5777, 0.9264],
        [0.8142, 0.1204, 0.2852],
        [0.9062, 0.1523, 0.1472]])

In [9]:
X.shape

(5, 3)

In [10]:
Y.shape

torch.Size([5, 3])

In [11]:
# numpy
X.T @ X

array([[1.25317566, 1.35734331, 0.7249246 ],
       [1.35734331, 2.450437  , 1.61511273],
       [0.7249246 , 1.61511273, 1.51047787]])

In [12]:
# torch
Y.t() @ Y

tensor([[1.9408, 0.7742, 0.9105],
        [0.7742, 0.7422, 0.6189],
        [0.9105, 0.6189, 1.0897]])

In [13]:
# numpy
inv(X.T @ X)

array([[ 2.2897651 , -1.84272651,  0.8714487 ],
       [-1.84272651,  2.86524734, -2.17934981],
       [ 0.8714487 , -2.17934981,  2.57412643]])

In [14]:
# torch
torch.inverse(Y.t() @ Y)

tensor([[ 0.9891, -0.6507, -0.4568],
        [-0.6507,  2.9878, -1.1534],
        [-0.4568, -1.1534,  1.9545]])

## More on PyTorch Tensors

Operations are also available as methods.

In [15]:
A = torch.eye(3)
A.add(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [16]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Any operation that mutates a tensor in-place has a `_` suffix.

In [17]:
A.add_(1)
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

## Indexing and broadcasting
It works as expected/like numpy:

In [18]:
A[0, 0]

tensor(2.)

In [19]:
A[0]

tensor([2., 1., 1.])

In [20]:
A[0:2]

tensor([[2., 1., 1.],
        [1., 2., 1.]])

In [21]:
A[:, 1:3]

tensor([[1., 1.],
        [2., 1.],
        [1., 2.]])

## Converting

In [22]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
# torch --> numpy
B = A.numpy()
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

Note: torch and numpy can share the same memory / zero-copy

In [24]:
A.add_(.5)
A

tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])

In [25]:
B

array([[1.5, 0.5, 0.5],
       [0.5, 1.5, 0.5],
       [0.5, 0.5, 1.5]], dtype=float32)

In [26]:
# numpy --> torch
torch.from_numpy(np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

## Much more

In [27]:
[o for o  in dir(torch) if not o.startswith("_")]

['AVG',
 'AggregationType',
 'Argument',
 'ArgumentSpec',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BenchmarkConfig',
 'BenchmarkExecutionStats',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'ByteStorage',
 'ByteTensor',
 'CharStorage',
 'CharTensor',
 'ClassType',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'CudaBFloat16StorageBase',
 'CudaBoolStorageBase',
 'CudaByteStorageBase',
 'CudaCharStorageBase',
 'CudaDoubleStorageBase',
 'CudaFloatStorageBase',
 'CudaHalfStorageBase',
 'CudaIntStorageBase',
 'CudaLongStorageBase',
 'CudaShortStorageBase',
 'DictType',
 'DoubleStorage',
 'DoubleTensor',
 'ErrorReport',
 'ExecutionPlan',
 'ExtraFilesMap',
 'FatalError',
 'FileCheck',
 'FloatStorage',
 'FloatTensor',
 'FloatType',
 'Function',
 'FunctionSchema',
 'Future',
 'Generator',
 'Gradient',
 'Graph',
 'GraphExecutorState',
 'HalfStorage',
 'HalfStorageBase',
 'HalfTensor',
 'IODescriptor',
 'IntStorage',
 'IntTensor',
 'IntType',
 'JITException',
 'ListType',
 'Lock

In [28]:
[o for o  in dir(A) if not o.startswith("_")]

['T',
 'abs',
 'abs_',
 'acos',
 'acos_',
 'add',
 'add_',
 'addbmm',
 'addbmm_',
 'addcdiv',
 'addcdiv_',
 'addcmul',
 'addcmul_',
 'addmm',
 'addmm_',
 'addmv',
 'addmv_',
 'addr',
 'addr_',
 'align_as',
 'align_to',
 'all',
 'allclose',
 'any',
 'apply_',
 'argmax',
 'argmin',
 'argsort',
 'as_strided',
 'as_strided_',
 'asin',
 'asin_',
 'atan',
 'atan2',
 'atan2_',
 'atan_',
 'backward',
 'baddbmm',
 'baddbmm_',
 'bernoulli',
 'bernoulli_',
 'bfloat16',
 'bincount',
 'bitwise_not',
 'bitwise_not_',
 'bmm',
 'bool',
 'byte',
 'cauchy_',
 'ceil',
 'ceil_',
 'char',
 'cholesky',
 'cholesky_inverse',
 'cholesky_solve',
 'chunk',
 'clamp',
 'clamp_',
 'clamp_max',
 'clamp_max_',
 'clamp_min',
 'clamp_min_',
 'clone',
 'coalesce',
 'contiguous',
 'copy_',
 'cos',
 'cos_',
 'cosh',
 'cosh_',
 'cpu',
 'cross',
 'cuda',
 'cumprod',
 'cumsum',
 'data',
 'data_ptr',
 'dense_dim',
 'dequantize',
 'det',
 'detach',
 'detach_',
 'device',
 'diag',
 'diag_embed',
 'diagflat',
 'diagonal',
 'diga

# But what about the GPU?
How do I use the GPU?

If you have a GPU make sure that the right pytorch is installed
(check https://pytorch.org/ for details).

In [29]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

If you have a GPU you should get something like: 
`device(type='cuda', index=0)`

You can move data to the GPU by doing `.to(device)`.

In [30]:
data = torch.eye(3)
data.to(device)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')

Now the computation happens on the GPU.

In [31]:
res = data + data
res

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [32]:
res.device

device(type='cpu')

Note: before `v0.4` one had to use `.cuda()` and `.cpu()` to move stuff to and from the GPU.
This littered the code with many:
```python
if CUDA:
    model = model.cuda()
```

# Automatic differentiation with `autograd`
Prior to `v0.4` PyTorch used the class `Variable` to record gradients. You had to wrap `Tensor`s in `Variable`s.
`Variable`s behaved exactly like `Tensors`.

With `v0.4` `Tensor` can record gradients directly if you tell it do do so, e.g. `torch.ones(3, requires_grad=True)`.
There is no need for `Variable` anymore.
Many tutorials still use `Variable`, be aware!

Ref:
- https://pytorch.org/docs/stable/autograd.html
- https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

You rarely use `torch.autograd` directly.
Pretty much everything is part or `torch.Tensor` now.
Simply add `requires_grad=True` to the tensors you want to calculate the gradients for.
`nn.Module` track gradients automatically.

In [33]:
from torch import autograd

In [34]:
x = torch.tensor(2.)
x

tensor(2.)

In [35]:
x = torch.tensor(2., requires_grad=True)
x

tensor(2., requires_grad=True)

In [36]:
print(x.requires_grad)

True


In [37]:
print(x.grad)

None


In [38]:
y = x ** 2

print("Grad of x:", x.grad)

Grad of x: None


In [39]:
y = x ** 2
y.backward()

print("Grad of x:", x.grad)

Grad of x: tensor(4.)


In [40]:
# What is going to happen here?
# x = torch.tensor(2.)
# x.backward()

In [41]:
# Don't record the gradient
# Useful for inference

params = torch.tensor(2., requires_grad=True)

with torch.no_grad():
    y = x * x
    print(x.grad_fn)

None


`nn.Module` and `nn.Parameter` keep track of gradients for you.

In [42]:
lin = nn.Linear(2, 1, bias=True)
lin.weight

Parameter containing:
tensor([[-0.5266,  0.5209]], requires_grad=True)

In [43]:
type(lin.weight)

torch.nn.parameter.Parameter

In [44]:
isinstance(lin.weight, torch.FloatTensor)

True

# Exercise
- Do you remember the analytical solution to solve for the parameters of linear regression? Implement it.